/* eslint-disable @eslint-community/eslint-comments/disable-enable-pair -- auto generated */

/* eslint-disable @eslint-community/eslint-comments/no-unlimited-disable  -- auto generated */

/* eslint-disable -- auto generated  */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.
// Import Routes
import { Route as rootRoute } from './app/__root';
import { Route as DungeonImport } from './app/dungeon';
import { Route as IndexImport } from './app/index';

// Create/Update Routes

const DungeonRoute = DungeonImport.update({
  id: '/dungeon',
  path: '/dungeon',
  getParentRoute: () => rootRoute,
} as any);

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexImport;
      parentRoute: typeof rootRoute;
    };
    '/dungeon': {
      id: '/dungeon';
      path: '/dungeon';
      fullPath: '/dungeon';
      preLoaderRoute: typeof DungeonImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/dungeon': typeof DungeonRoute;
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/dungeon': typeof DungeonRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  '/': typeof IndexRoute;
  '/dungeon': typeof DungeonRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: '/' | '/dungeon';
  fileRoutesByTo: FileRoutesByTo;
  to: '/' | '/dungeon';
  id: '__root__' | '/' | '/dungeon';
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  DungeonRoute: typeof DungeonRoute;
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DungeonRoute: DungeonRoute,
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/dungeon"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/dungeon": {
      "filePath": "dungeon.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
